### ISSUE TITLE
All of the quickstart pages are broken (404)

### ISSUE THREAD

**Issue by SCKelemen** [jhu-information-security-institute/CryptoDoneRight#30]
## 1. DESCRIPTION
> You can have the description of your issue here

All of the quickstart pages are broken (404)

## 2. TYPE OF ISSUE

- [ ] Feedback (Good or Bad!)
- [ ] Request for Content
- [ ] Error in Content
- [ ] Outdated Content
- [ ] Page Layout
- [X] URL Linking Issue
- [ ] Code Bug (e.g. Jekyll Template)
- [X] Other

All of the quickstart pages are broken (404)

## 3. ADDITIONAL DETAILS
> If there's a problem with the site, please identify OS and Browser. If relevant or helpful include the steps the reproduce the problem.

https://cryptodoneright.org/quickstarts/dev
https://cryptodoneright.org/quickstarts/manager
https://cryptodoneright.org/quickstarts/it

They all need .html at the end fam
## 4. CHECK LIST

- [X] I have looked for existing issues or change requests to prevent duplicate submissions.
- [X] I have provided all of the known, relevant details within this issue.

## 0. Instructions
This template shows the proper format to make an issue for [CryptoDoneRight.org](https://cryptodoneright.org/)

1. Delete the header with the "name" and "about"
2. Write a description of your issue in the "Description" section
3. Identify the type of issue in the "Type of Issue" section (mark all that apply)
4. If applicable, add additional details. Otherwise, enter "None" or "N/A".
5. Delete this Instructions section.

When marking a checkbox, put an "x" in the brackets with no spaces:

- [x] This is correctly checked
- [ ] This is correctly un-checked
- [ x ] This is not correctly checked

You are now ready to submit! We look forward to your input!

**Comment by elliemdaw** [comment]
Thank you for opening this issue! I just pushed a fix, so it should be updated now. Be sure to clear your cache if you aren't seeing the changes :)
