### ISSUE TITLE
Entropy Slides

### ISSUE THREAD

**Issue by rt5v3y02fk** [jhu-information-security-institute/CryptoDoneRight#9]
The entropy slides are attached.

[Entropy_SecCon_01022018v2.pptx](https://github.com/jhu-information-security-institute/ciscodemo/files/2532111/Entropy_SecCon_01022018v2.pptx)

I uploaded the Entropy Presentation to slideshare.  The link to it is here:  https://www.slideshare.net/dbakernc/entropy-sec-con01022018v2public-122946147

Thanks,

Debra

**Comment by elliemdaw** [comment]
I added some info about entropy! Will push today sometime :)
